CREATE TABLE IF NOT EXISTS T_LOG4J(
	ID INT NOT NULL AUTO_INCREMENT,
	STAMP TIMESTAMP,
	THREAD VARCHAR(100),
	INFO_LEVEL VARCHAR(10),
	CLASS VARCHAR(1000),
		VARCHAR(4000),
	PRIMARY KEY(ID)
)ENGINE = INNODB DEFAULT CHARACTER SET UTF8;